<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Guard\Doctrine\Controller;

use MSBios\Guard\Controller\IndexController as DefaultIndexController;

/**
 * Class IndexController
 * @package MSBios\Guard\Doctrine\Controller
 */
class IndexController extends DefaultIndexController
{
    /**
     * @return \Zend\Http\Response|\Zend\View\Model\ViewModel
     */
//    public function indexAction()
//    {
//        return parent::indexAction(); // TODO: Change the autogenerated stub
//    }

}